#criarbanco mysql pod
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: fq1444/projeto-backend:1.0
        args: 
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
         - name: mysql-dados
           mountPath: /var/lib/mysql/
      volumes:  
       - name: mysql-dados
         persistentVolumeClaim:
           claimName: mysql-dados
